apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3-pods-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector: 
    matchLabels:
      app: nginx-app
  template:
    metadata: 
      labels:
        app: nginx-app
    spec: 
      containers:
      - name: nginx-container
        image: nginx:alpine
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits: 
            cpu: 200m
            memory: 128Mi
        ports:
          - containerPort: 80
